---@type QuestieDB
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")
---@type ZoneDB
local ZoneDB = QuestieLoader:ImportModule("ZoneDB")

if not QuestieLoader then
    print("Questie-335 is required for Questie-AshenOrder to function. Please enable the Questie-335 addon.")
    return
end

QuestieCompat.RegisterCorrection("questData", function()
    local questKeys = QuestieDB.questKeys
    local sortKeys = QuestieDB.sortKeys
    local raceIDs = QuestieDB.raceKeys
    local factionIDs = QuestieDB.factionIDs
    local zoneIDs = ZoneDB.zoneIDs
 
    return {
        [9] = {
            [questKeys.nextQuestInChain] = 41,
        },
        [41] = {
            [questKeys.name] = "It's Over 9000",
            [questKeys.startedBy] = {{233}},
            [questKeys.finishedBy] = {{233}},
            [questKeys.requiredLevel] = 8,
            [questKeys.questLevel] = 20,
            [questKeys.preQuestSingle] = {9},
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Farmer Saldean wants you to kill the Foe Reaper 9001."},
            [questKeys.objectives] = {{{900003}}},
            [questKeys.zoneOrSort] = zoneIDs.WESTFALL,
            [questKeys.reputationReward] = {{72, 250}},
        },
        [42] = {
            [questKeys.name] = "The Stalking Shadow",
            [questKeys.startedBy] = {{234}},
            [questKeys.finishedBy] = {{234}},
            [questKeys.requiredLevel] = 10,
            [questKeys.questLevel] = 20,
            [questKeys.objectivesText] = {"Slay the Lithe Stalker prowling the Eastern roads."},
            [questKeys.objectives] = {{{400015}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
            [questKeys.reputationReward] = {{72, 250}},
        },
        [109] = {
            [questKeys.zoneOrSort] = zoneIDs.WESTFALL,
        },
        [30000] = {
            [questKeys.name] = "Battle for Westfall",
            [questKeys.startedBy] = {{234}},
            [questKeys.finishedBy] = {{234}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 20,
            [questKeys.objectivesText] = {"Gryan Stoutmantle wants you to venture forth into Westfall and slay 15 Ghouls during the Kalimdor Scourge Invasion."},
            [questKeys.objectives] = {{{400010}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30001] = {
            [questKeys.name] = "Calming the Chaos",
            [questKeys.startedBy] = {{1284}},
            [questKeys.finishedBy] = {{5566}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.nextQuestInChain] = 30002,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Bring 8 Soothing Spices to Herbalist Tannysa."},
            [questKeys.objectives] = {{{3713}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30002] = {
            [questKeys.name] = "Calming the Chaos",
            [questKeys.startedBy] = {{5566}},
            [questKeys.finishedBy] = {{1284}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.preQuestSingle] = {30001},
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Calm 8 Panicked Stormwind Citizens."},
            [questKeys.objectives] = {{{400028}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30003] = {
            [questKeys.name] = "Bolstering our Forces",
            [questKeys.startedBy] = {{1284}},
            [questKeys.finishedBy] = {{1284}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Use the ribbon on 10 Stormwind Guards during the ongoing Scourge attack on Stormwind City."},
            [questKeys.objectives] = {{{68}}},
            [questKeys.sourceItemId] = 60084,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30004] = {
            [questKeys.name] = "Trapping our Enemies",
            [questKeys.startedBy] = {{12480}},
            [questKeys.finishedBy] = {{12480}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Set 6 Traps against the Scourge."},
            [questKeys.objectives] = {{{400034}}},
            [questKeys.sourceItemId] = 60085,
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30005] = {
            [questKeys.name] = "Calming the Chaos",
            [questKeys.startedBy] = {{400064}},
            [questKeys.finishedBy] = {{5958}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.nextQuestInChain] = 30006,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Bring 8 Runes of Teleportation to Thuul, the mage trainer, in the Valley of Spirits."},
            [questKeys.objectives] = {{{17031}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30006] = {
            [questKeys.name] = "Calming the Chaos",
            [questKeys.startedBy] = {{5958}},
            [questKeys.finishedBy] = {{400064}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.preQuestSingle] = {30005},
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Teleport 8 Orgrimmar Citizens to safety."},
            [questKeys.objectives] = {{{400067}}},
            [questKeys.sourceItemId] = 65002,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30007] = {
            [questKeys.name] = "Zap It to Win It!",
            [questKeys.startedBy] = {{400064}},
            [questKeys.finishedBy] = {{9317}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.nextQuestInChain] = 30008,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Speak to Rilli Greasybob about the Turret Recharger."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30008] = {
            [questKeys.name] = "Zap It to Win It!",
            [questKeys.startedBy] = {{9317}},
            [questKeys.finishedBy] = {{400064}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.preQuestSingle] = {30007},
            [questKeys.nextQuestInChain] = 30009,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Recharge 5 fallen turrets in Orgrimmar."},
            [questKeys.objectives] = {{{400037}}},
            [questKeys.sourceItemId] = 65003,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30009] = {
            [questKeys.name] = "Trapping our Enemies",
            [questKeys.startedBy] = {{400064}},
            [questKeys.finishedBy] = {{400064}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.preQuestSingle] = {30008},
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Set 6 Traps against the Scourge."},
            [questKeys.objectives] = {{{400034}}},
            [questKeys.sourceItemId] = 60085,
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30010] = {
            [questKeys.name] = "Fortifying our Forces",
            [questKeys.startedBy] = {{400064}},
            [questKeys.finishedBy] = {{400064}},
            [questKeys.requiredLevel] = 50,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Use the Shadow-Drenched Cloth on 15 city defenders during the ongoing Scourge attack."},
            [questKeys.objectives] = {{{3296}}},
            [questKeys.sourceItemId] = 60115,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30011] = {
            [questKeys.name] = "Warn the Stragglers!",
            [questKeys.startedBy] = {{344}},
            [questKeys.finishedBy] = {{344}},
            [questKeys.requiredLevel] = 16,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Tell 8 villagers to flee to safety at the inn."},
            [questKeys.objectives] = {{{400080}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30012] = {
            [questKeys.name] = "The Final Fortification",
            [questKeys.startedBy] = {{344}},
            [questKeys.finishedBy] = {{344}},
            [questKeys.requiredLevel] = 16,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Set up 5 Barriers at Strategic Locations in Redridge."},
            [questKeys.objectives] = {{{400095}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30013] = {
            [questKeys.name] = "The Blighted Battle",
            [questKeys.startedBy] = {{344}},
            [questKeys.finishedBy] = {{344}},
            [questKeys.requiredLevel] = 16,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Kill 3 Blighted Zombies and 10 Skeletal Warriors."},
            [questKeys.objectives] = {{{400077},{400016}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30014] = {
            [questKeys.name] = "An Unsettling Discovery",
            [questKeys.startedBy] = {{400097}},
            [questKeys.finishedBy] = {{400096}},
            [questKeys.requiredLevel] = 20,
            [questKeys.questLevel] = 25,
            [questKeys.nextQuestInChain] = 30015,
            [questKeys.objectivesText] = {"Take the skull to someone in Lakeshire."},
            [questKeys.objectives] = {{{65005}}},
            [questKeys.sourceItemId] = 65005,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30015] = {
            [questKeys.name] = "Eternal Embers",
            [questKeys.startedBy] = {{400096}},
            [questKeys.finishedBy] = {{400096}},
            [questKeys.requiredLevel] = 20,
            [questKeys.questLevel] = 30,
            [questKeys.preQuestSingle] = {30014},
            [questKeys.nextQuestInChain] = 30016,
            [questKeys.objectivesText] = {"Gather 8 Eternal Embers from Crimson Whelps in Wetlands."},
            [questKeys.objectives] = {nil,nil,{{65006}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30016] = {
            [questKeys.name] = "Sanctified Waters",
            [questKeys.startedBy] = {{400096}},
            [questKeys.finishedBy] = {{400096}},
            [questKeys.requiredLevel] = 20,
            [questKeys.questLevel] = 30,
            [questKeys.preQuestSingle] = {30015},
            [questKeys.nextQuestInChain] = 30017,
            [questKeys.objectivesText] = {"Fill the vial at the Moonwell."},
            [questKeys.objectives] = {nil,nil,{{60119}}},
            [questKeys.sourceItemId] = 60118,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30017] = {
            [questKeys.name] = "Keeper of the Crusader's Tome",
            [questKeys.startedBy] = {{400096}},
            [questKeys.finishedBy] = {{400096}},
            [questKeys.requiredLevel] = 20,
            [questKeys.questLevel] = 30,
            [questKeys.preQuestSingle] = {30016},
            [questKeys.nextQuestInChain] = 30018,
            [questKeys.objectivesText] = {"Obtain the Crusader's Tome from Keeper Krayle."},
            [questKeys.objectives] = {nil,nil,{{65007}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30018] = {
            [questKeys.name] = "At Long Last",
            [questKeys.startedBy] = {{400096}},
            [questKeys.finishedBy] = {{400096}},
            [questKeys.requiredLevel] = 20,
            [questKeys.questLevel] = 30,
            [questKeys.preQuestSingle] = {30017},
            [questKeys.objectivesText] = {"Cleanse the soul of Thalgorath the Defiler."},
            [questKeys.objectives] = {{{400103}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30019] = {
            [questKeys.name] = "Villagers Armed",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{3429}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Arm and Direct the Villagers."},
            [questKeys.objectives] = {{{400104}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30020] = {
            [questKeys.name] = "Filling the Gaps",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{3429}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Gather 20 logs and erect two barriers at strategic points."},
            [questKeys.objectives] = {{{400095}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30021] = {
            [questKeys.name] = "The Battle for Crossroads",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{3429}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.objectivesText] = {"Kill Various Scourge Invaders."},
            [questKeys.objectives] = {{{400112},{400016},{400077},{400114}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30022] = {
            [questKeys.name] = "Abomination Annihilation",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{400118}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.nextQuestInChain] = 30023,
            [questKeys.objectivesText] = {"Kill Sutures and return any information you may find."},
            [questKeys.objectives] = {{{400113}}},
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30023] = {
            [questKeys.name] = "Abomination Annihilation",
            [questKeys.startedBy] = {{400118}},
            [questKeys.finishedBy] = {{3429}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.preQuestSingle] = {30022},
            [questKeys.nextQuestInChain] = 30024,
            [questKeys.objectivesText] = {"Bring back what you've found out to Thork."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30024] = {
            [questKeys.name] = "Decoding the Emblem",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{8385}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.preQuestSingle] = {30023},
            [questKeys.nextQuestInChain] = 30025,
            [questKeys.objectivesText] = {"Speak with Mura about decoding the Emblem."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30025] = {
            [questKeys.name] = "Unraveling the Scourge's Secrets",
            [questKeys.startedBy] = {{3429}},
            [questKeys.finishedBy] = {{8385}},
            [questKeys.requiredLevel] = 14,
            [questKeys.questLevel] = 25,
            [questKeys.preQuestSingle] = {30024},
            [questKeys.objectivesText] = {"To be Continued"},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30026] = {
            [questKeys.name] = "Remnants of the Rampage",
            [questKeys.startedBy] = {{400120}},
            [questKeys.finishedBy] = {{1748}},
            [questKeys.requiredLevel] = 45,
            [questKeys.questLevel] = 55,
            [questKeys.objectivesText] = {"Go and Speak with Bolvar."},
            [questKeys.objectives] = {nil,nil,{{36785}}},
            [questKeys.sourceItemId] = 36785,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30027] = {
            [questKeys.name] = "A Frost Wyrm's Demise",
            [questKeys.startedBy] = {{400121}},
            [questKeys.finishedBy] = {{4949}},
            [questKeys.requiredLevel] = 45,
            [questKeys.questLevel] = 55,
            [questKeys.objectivesText] = {"Go and Speak with Thrall."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30028] = {
            [questKeys.name] = "Stemming the Scourge Tide",
            [questKeys.startedBy] = {{400064}},
            [questKeys.finishedBy] = {{400064}},
            [questKeys.requiredLevel] = 45,
            [questKeys.questLevel] = 55,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.objectivesText] = {"Kill 30 Scourge Forces in Orgrimmar."},
            [questKeys.objectives] = {{{300000}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30029] = {
            [questKeys.name] = "Purge the Unholy Scourge",
            [questKeys.startedBy] = {{1284}},
            [questKeys.finishedBy] = {{1284}},
            [questKeys.requiredLevel] = 45,
            [questKeys.questLevel] = 55,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Kill 30 Scourge Forces in Stormwind."},
            [questKeys.objectives] = {{{300000}}},
            [questKeys.questFlags] = 4096, -- Daily
            [questKeys.specialFlags] = 1, -- Repeatable
            [questKeys.zoneOrSort] = sortKeys.SCOURGE_INVASION,
        },
        [30030] = {
            [questKeys.name] = "Flowers for a Friend",
            [questKeys.startedBy] = {{100140}},
            [questKeys.finishedBy] = {{100157}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 3,
            [questKeys.nextQuestInChain] = 30031,
            [questKeys.objectivesText] = {"Meet Eldreth Spellshard at King Llane's Tomb with Kloveriell's Wildflowers."},
            [questKeys.objectives] = {nil,nil,{{800069}}},
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30031] = {
            [questKeys.name] = "Touched by Shadows",
            [questKeys.startedBy] = {{100157}},
            [questKeys.finishedBy] = {{100139}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 3,
            [questKeys.preQuestSingle] = {30030},
            [questKeys.nextQuestInChain] = 30032,
            [questKeys.objectivesText] = {"Speak with High Priestess Aquila Empyrean at the High Elven Embassy in Stormwind City regarding the shadowy presence."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30032] = {
            [questKeys.name] = "Harvesting Light",
            [questKeys.startedBy] = {{100139}},
            [questKeys.finishedBy] = {{100139}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 3,
            [questKeys.preQuestSingle] = {30031},
            [questKeys.objectivesText] = {"Collect 5 Light-infused Crystals."},
            [questKeys.objectives] = {nil,nil,{{800070}}},
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30033] = {
            [questKeys.name] = "Encoded Shadows",
            [questKeys.startedBy] = {{1500017}},
            [questKeys.finishedBy] = {{100147}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 4,
            [questKeys.nextQuestInChain] = 30034,
            [questKeys.objectivesText] = {"Speak with Elandra Sagequill."},
            [questKeys.objectives] = {nil,nil,{{800075}}},
            [questKeys.sourceItemId] = 800075,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30034] = {
            [questKeys.name] = "Encoded Shadows",
            [questKeys.startedBy] = {{100147}},
            [questKeys.finishedBy] = {{100141}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 4,
            [questKeys.preQuestSingle] = {30033},
            [questKeys.nextQuestInChain] = 30035,
            [questKeys.objectivesText] = {"Take the note to Raelis Silentstep."},
            [questKeys.objectives] = {nil,nil,{{800075}}},
            [questKeys.sourceItemId] = 800075,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30035] = {
            [questKeys.name] = "Defias Infiltration",
            [questKeys.startedBy] = {{100141}},
            [questKeys.finishedBy] = {{100141}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 5,
            [questKeys.preQuestSingle] = {30034},
            [questKeys.nextQuestInChain] = 30036,
            [questKeys.objectivesText] = {"Interrogate Stormwind Guards for Information."},
            [questKeys.objectives] = {{{400095}}},
            [questKeys.sourceItemId] = 800081,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30036] = {
            [questKeys.name] = "Defias Infiltration",
            [questKeys.startedBy] = {{100141}},
            [questKeys.finishedBy] = {{100141}},
            [questKeys.requiredLevel] = 2,
            [questKeys.questLevel] = 6,
            [questKeys.preQuestSingle] = {30035},
            [questKeys.nextQuestInChain] = 30037,
            [questKeys.objectivesText] = {"Remove the Defias' Point of Entry."},
            [questKeys.objectives] = {{{400095}}},
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30037] = {
            [questKeys.name] = "Defias Infiltration",
            [questKeys.startedBy] = {{100141}},
            [questKeys.finishedBy] = {{100141}},
            [questKeys.requiredLevel] = 2,
            [questKeys.questLevel] = 6,
            [questKeys.preQuestSingle] = {30036},
            [questKeys.nextQuestInChain] = 30038,
            [questKeys.objectivesText] = {"Interrogate the implicated members of the House of Nobles."},
            [questKeys.objectives] = {{{110000},{110001}},nil,{{800077}}},
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30038] = {
            [questKeys.name] = "Ritual at the Keep",
            [questKeys.startedBy] = {{100141}},
            [questKeys.finishedBy] = {{100141}},
            [questKeys.requiredLevel] = 4,
            [questKeys.questLevel] = 7,
            [questKeys.preQuestSingle] = {30037},
            [questKeys.nextQuestInChain] = 30039,
            [questKeys.objectivesText] = {"Disrupt the Defias Ritual."},
            [questKeys.objectives] = {{{100164},{100165},{100166}}},
            [questKeys.sourceItemId] = 800079,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30039] = {
            [questKeys.name] = "Report to Aquila Empyrean",
            [questKeys.startedBy] = {{100141}},
            [questKeys.finishedBy] = {{100139}},
            [questKeys.requiredLevel] = 2,
            [questKeys.questLevel] = 7,
            [questKeys.preQuestSingle] = {30038},
            [questKeys.objectivesText] = {"Speak with Aquila."},
            [questKeys.objectives] = nil,
            [questKeys.zoneOrSort] = sortKeys.EXILED_ENCLAVE,
        },
        [30040] = {
            [questKeys.name] = "A Stew for the Streets",
            [questKeys.startedBy] = {{1405}},
            [questKeys.finishedBy] = {{1402}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 5,
            [questKeys.objectivesText] = {"Get Ingredients for McNab's Squirrely-Rat Stew."},
            [questKeys.objectives] = {nil,nil,{{800072},{800071}}},
            [questKeys.zoneOrSort] = sortKeys.STORMWIND_CITY,
        },
        [30041] = {
            [questKeys.name] = "Pumpkin Harvest",
            [questKeys.startedBy] = {{100167}},
            [questKeys.finishedBy] = {{100167}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 4,
            [questKeys.objectivesText] = {"Gather some Pumpkins for Farmer David."},
            [questKeys.objectives] = {nil,nil,{{4656}}},
            [questKeys.zoneOrSort] = sortKeys.STORMWIND_CITY,
        },
        [30042] = {
            [questKeys.name] = "Wolves at the Walls",
            [questKeys.startedBy] = {{100167}},
            [questKeys.finishedBy] = {{100167}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 2,
            [questKeys.objectivesText] = {"Clear out five wolves."},
            [questKeys.objectives] = {{{299}}},
            [questKeys.zoneOrSort] = sortKeys.STORMWIND_CITY,
        },
        [30043] = {
            [questKeys.name] = "From Sea to Tavern",
            [questKeys.startedBy] = {{1400060}},
            [questKeys.finishedBy] = {{1327}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 4,
            [questKeys.objectivesText] = {"Deliver the fish to the Pig and Whistle."},
            [questKeys.objectives] = {nil,nil,{{800083}}},
            [questKeys.sourceItemId] = 800083,
            [questKeys.zoneOrSort] = sortKeys.STORMWIND_CITY,
        },
        [39534] = {
            [questKeys.name] = "Crushing Crystallon: A Stonetalon Showdown",
            [questKeys.startedBy] = {nil,{888649}},
            [questKeys.finishedBy] = {{7999}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.questFlags] = 64, -- Raid
            [questKeys.objectivesText] = {"Slay Crystallon in Stonetalon Mountains. Report to Tyrande Whisperwind in Darnassus should you succeed."},
            [questKeys.objectives] = {{{810119}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [39535] = {
            [questKeys.name] = "Crushing Crystallon: A Stonetalon Showdown",
            [questKeys.startedBy] = {nil,{888650}},
            [questKeys.finishedBy] = {{11860}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.questFlags] = 64, -- Raid
            [questKeys.objectivesText] = {"Slay Crystallon in Stonetalon Mountains. Report to Maggran Earthbinder at Sun Rock Retreat should you succeed."},
            [questKeys.objectives] = {{{810119}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [39536] = {
            [questKeys.name] = "Vanquishing Volchan: The Burning Battle",
            [questKeys.startedBy] = {nil,{888650}},
            [questKeys.finishedBy] = {{10267}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.questFlags] = 64, -- Raid
            [questKeys.objectivesText] = {"Kill Volchan in Burning Steppes. Should you succeed, seek out Tinkee Steamboil. She was last seen at Flame Crest."},
            [questKeys.objectives] = {{{10119}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [39537] = {
            [questKeys.name] = "Vanquishing Volchan: The Burning Battle",
            [questKeys.startedBy] = {nil,{888649}},
            [questKeys.finishedBy] = {{9560}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.questFlags] = 64, -- Raid
            [questKeys.objectivesText] = {"Kill Volchan in Burning Steppes. Should you succeed, seek out Marshal Maxwell at Morgan's Vigil."},
            [questKeys.objectives] = {{{10119}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [39538] = {
            [questKeys.name] = "Subduing Setis: The Silithid Standoff",
            [questKeys.startedBy] = {nil,{888649,888650}},
            [questKeys.finishedBy] = {{15191}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.questFlags] = 64, -- Raid
            [questKeys.objectivesText] = {"Slay Setis in Silithus. Should you succeed, speak with Windcaller Proudhorn at Cenarion Hold."},
            [questKeys.objectives] = {{{14471}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [41538] = {
            [questKeys.name] = "Nefarian Must Die!",
            [questKeys.startedBy] = {nil,{888649}},
            [questKeys.finishedBy] = {{14721}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.questFlags] = 32832, -- Weekly/Raid
            [questKeys.objectivesText] = {"Defeat Nefarian in Blackwing Lair."},
            [questKeys.objectives] = {{{11583}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [41539] = {
            [questKeys.name] = "Nefarian Must Die!",
            [questKeys.startedBy] = {nil,{888650}},
            [questKeys.finishedBy] = {{4949}},
            [questKeys.requiredLevel] = 60,
            [questKeys.questLevel] = 60,
            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
            [questKeys.questFlags] = 32832, -- Weekly/Raid
            [questKeys.objectivesText] = {"Defeat Nefarian in Blackwing Lair."},
            [questKeys.objectives] = {{{11583}}},
            [questKeys.zoneOrSort] = sortKeys.EPIC,
        },
        [50000] = {
            [questKeys.name] = "Echoes of Balance",
            [questKeys.startedBy] = {{100140}},
            [questKeys.finishedBy] = {{100140}},
            [questKeys.requiredLevel] = 37,
            [questKeys.questLevel] = 40,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Kloveriell wants you to slay Glutton in Razorfen Downs."},
            [questKeys.objectives] = {{{8567}}},
            [questKeys.zoneOrSort] = zoneIDs.RAZORFEN_DOWNS,
        },
        [50176] = {
            [questKeys.name] = "Rognar the Terrible",
            [questKeys.startedBy] = {{240}},
            [questKeys.finishedBy] = {{240}},
            [questKeys.requiredLevel] = 5,
            [questKeys.questLevel] = 12,
            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
            [questKeys.objectivesText] = {"Defeat Rognar the Terrible and retrieve his claw as proof of your deed."},
            [questKeys.objectives] = {nil,nil,{{801931}}},
            [questKeys.zoneOrSort] = zoneIDs.ELWYNN_FOREST,
        },
    }
end)