import argparse
import csv
import sys
from pathlib import Path


sys.dont_write_bytecode = True
TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from validate_acore_quest_metadata import load_acore_sql_table  # noqa: E402


CSV_COLUMNS = ["ID", *[f"Difficulty_{index}" for index in range(1, 11)]]
DEFAULT_OUTPUT = Path("Database/QuestXP/DB/xpDB-azerothcore-wotlk.lua")


def parse_int(value, label):
    try:
        return int(value)
    except (TypeError, ValueError) as error:
        raise ValueError(f"{label} must be an integer, got {value!r}") from error


def load_quest_xp_csv(path):
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames != CSV_COLUMNS:
            raise ValueError(
                f"{path} must have columns {', '.join(CSV_COLUMNS)}; "
                f"got {', '.join(reader.fieldnames or [])}"
            )

        xp_by_level = {}
        for line_number, row in enumerate(reader, start=2):
            level = parse_int(row["ID"], f"{path}:{line_number} ID")
            if level <= 0:
                raise ValueError(f"{path}:{line_number} ID must be positive")
            if level in xp_by_level:
                raise ValueError(f"{path}:{line_number} duplicates level {level}")

            rewards = []
            for index in range(1, 11):
                reward = parse_int(
                    row[f"Difficulty_{index}"],
                    f"{path}:{line_number} Difficulty_{index}",
                )
                if reward < 0:
                    raise ValueError(
                        f"{path}:{line_number} Difficulty_{index} must not be negative"
                    )
                rewards.append(reward)

            xp_by_level[level] = rewards

    if not xp_by_level:
        raise ValueError(f"{path} contains no XP rows")

    expected_levels = set(range(1, max(xp_by_level) + 1))
    missing_levels = sorted(expected_levels - set(xp_by_level))
    if missing_levels:
        raise ValueError(f"{path} is missing levels: {missing_levels}")

    return xp_by_level


def load_acore_quests(source_root):
    quest_template = (
        source_root / "data" / "sql" / "base" / "db_world" / "quest_template.sql"
    )
    if not quest_template.is_file():
        raise ValueError(f"Could not find AzerothCore quest_template at {quest_template}")

    raw_rows = load_acore_sql_table(
        source_root,
        "quest_template",
        include_modules=True,
    )
    if not raw_rows:
        raise ValueError(f"No AzerothCore quest_template rows were loaded from {source_root}")

    quests = {}
    for quest_id, row in raw_rows.items():
        quest_id = parse_int(quest_id, "quest_template ID")
        quest_level = parse_int(row.get("QuestLevel"), f"quest {quest_id} QuestLevel")
        reward_difficulty = parse_int(
            row.get("RewardXPDifficulty"),
            f"quest {quest_id} RewardXPDifficulty",
        )

        if not 0 <= reward_difficulty <= 9:
            raise ValueError(
                f"quest {quest_id} has unsupported RewardXPDifficulty "
                f"{reward_difficulty}; expected 0 through 9"
            )

        quests[quest_id] = (quest_level, reward_difficulty)

    return quests


def build_lua(quests, xp_by_level):
    lines = [
        "--! This file is automatically generated. Do not modify.",
        "-- Generated by tools/generate_acore_quest_xp.py from AzerothCore",
        "-- quest_template data and the WotLK QuestXP.dbc export.",
        "",
        "---@type QuestXP",
        'local QuestXP = QuestieLoader:ImportModule("QuestXP")',
        "",
        "-- questId = {QuestLevel, RewardXPDifficulty}",
        "QuestXP.db = {",
    ]

    for quest_id in sorted(quests):
        quest_level, reward_difficulty = quests[quest_id]
        lines.append(f"    [{quest_id}] = {{{quest_level}, {reward_difficulty}}},")

    lines.extend([
        "}",
        "",
        "-- QuestXP.dbc rows. Lua index 1 corresponds to RewardXPDifficulty 0.",
        "QuestXP.xpByLevel = {",
    ])

    for level in sorted(xp_by_level):
        rewards = ", ".join(str(reward) for reward in xp_by_level[level])
        lines.append(f"    [{level}] = {{{rewards}}},")

    lines.extend(["}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate AzerothCore WotLK quest XP data for Questie 335."
    )
    parser.add_argument(
        "--acore-source",
        required=True,
        type=Path,
        help="Path to the AzerothCore source tree.",
    )
    parser.add_argument(
        "--quest-xp-csv",
        required=True,
        type=Path,
        help="CSV export of the WotLK QuestXP.dbc table.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        type=Path,
        help=f"Generated Lua output (default: {DEFAULT_OUTPUT}).",
    )
    args = parser.parse_args()

    xp_by_level = load_quest_xp_csv(args.quest_xp_csv)
    quests = load_acore_quests(args.acore_source)
    output = build_lua(quests, xp_by_level)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")

    dynamic_quests = sum(level == -1 for level, _ in quests.values())
    print(
        f"Wrote {args.output} with {len(quests)} quests, "
        f"{dynamic_quests} dynamic quests, and {len(xp_by_level)} XP levels."
    )


if __name__ == "__main__":
    main()
